fi-cong-integration:
    channel: metlife.smtp
    docs-file-path: C:/Users/Vitalii_Kim/Desktop/winsw/Регистрация_30.08.13.xlsx
    export-order-cron: 0 30 15 * * ?
    lock-repeat-interval-in-millis: 5000
    sender-email: otvet.cl@metlife.ru
    update-state-in-docs-file-cron: 0 0/10 * * * ?
server:
    port: 8080
spring:
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: gzam_apnt_ds
        password: gzam_apnt_user
        url: jdbc:sqlserver://localhost:1433;databasename=eDelivery_EPAM
        username: gzam_apnt_user
    jackson:
        serialization:
            INDENT_OUTPUT: true
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect
                format_sql: true
                show_sql: true
                use_sql_comments: true
            org:
                hibernate:
                    flushMode: AUTO
    main:
        banner-mode: 'off'
    mandatory-file-encoding: UTF-8
